### ISSUE TITLE
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!

### ISSUE THREAD

**Issue by ashishtilara** [auth0/auth0-ionic#10]
while running this project in browser using `ionic serve`, I see this error...
can also see `tab/dash` flickering in address bar.

Is this expected?! How do I resolve this.

cheers

**Comment by ashishtilara** [comment]
um.. never mind, fixed it by setting 
`$urlRouterProvider.otherwise('/login');`

instead of 

`$urlRouterProvider.otherwise('/tab/dash');`

**Comment by javilopezc** [comment]
I came across the same issue, and the route change made them go away. Thanks!
