### ISSUE TITLE
about:blank page after sign up

### ISSUE THREAD

**Issue by palemium** [auth0/auth0-ionic#17]
@mgonto Do you guys still support ionic? Or can you recommend different approach to make signup work on ionic? 

After signup I see about::blank page on ios emulator with OK button. In Ionic View there is no even OK button shown. On Android it crashes after sign up in Ionic View.
![blank page after signup](http://take.ms/9AmO2)

**Comment by LDubya** [comment]
Myself and other testers have also gotten this screen after a new sign up.

**Comment by stockm** [comment]
I am also seeing this issue, is there anything we can do to work around this ?

**Comment by LDubya** [comment]
@palemium Have you found a solution for this? We've been stuck on this for weeks.

**Comment by rolodato** [comment]
@LDubya @stockm @palemium Try using the latest version of Lock and passing `sso: false` to the options for `show()` or `signin()`.

**Comment by stockm** [comment]
Thank you. That worked for me. Appreciate your help

**Comment by nicosabena** [comment]
The blank window issue that appeared with Lock v10 after a signup was fixed in [Lock v10.18](https://github.com/auth0/lock/releases/tag/v10.18.0).
